name: Update CSV

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour, you can adjust as needed
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download CSV from NetSuite
      run: |
        curl -o path/to/local.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vR4E5klg4xrK_-HSTwNy2YHyKGcstOURl43hzeznkIGHodhlqKqhI2u7zOcvQCAl6PcgQ3pNzVXTwrA/pub?gid=1173243566&single=true&output=csv'  # Replace with your actual URL

    - name: Commit and push changes
      run: |
        git config --local user.email "you@example.com"
        git config --local user.name "Your Name"
        git add path/to/local.csv
        git commit -m "Update CSV file"
        git push
